<?php


namespace App\Repository;


use Doctrine\ORM\EntityRepository;

class JeuxRepository extends EntityRepository
{
    public function getByName()
    {

    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}