<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHdLYXw1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHdLYXw1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHdLYXw1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHdLYXw1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHdLYXw1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HdLYXw1',
    'container.build_id' => '7bc3480b',
    'container.build_time' => 1581801127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHdLYXw1');
